# Generated by Django 2.1.7 on 2019-03-19 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0003_auto_20190314_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_sub', to='reqs.Subject'),
        ),
    ]
