# Generated by Django 2.1.7 on 2019-03-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0005_auto_20190319_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subjects',
        ),
    ]
