# Generated by Django 2.1.7 on 2019-03-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0006_remove_section_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Section',
            new_name='section',
        ),
    ]
