# Generated by Django 2.1.7 on 2019-03-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0008_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_cid',
        ),
    ]
