# Generated by Django 2.1.7 on 2019-09-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
